# More examples at: https://plawgo.pl/2021/04/13/visual-studio-code-rest-client/

### Get quotes (limited by default page number and page size)
GET {{baseUrl}}/api/quotes HTTP/1.1

### Get quotes filtered
GET {{baseUrl}}/api/quotes?filter_author=Unknown&filter_language=Latin HTTP/1.1

### Get quotes searched
GET {{baseUrl}}/api/quotes?search_text=first HTTP/1.1

### Get quotes filtered & searched
GET {{baseUrl}}/api/quotes?filter_author=Unknown&filter_language=Latin&search_text=astra HTTP/1.1

### Get quotes paged
GET {{baseUrl}}/api/quotes?pageNumber=2&pageSize=2 HTTP/1.1

### Get quotes in the XML format
GET {{baseUrl}}/api/quotes HTTP/1.1
Accept: application/xml

### Get a single quote
GET {{baseUrl}}/api/quotes/{{getQuoteId}} HTTP/1.1

### Create a new quote
POST {{baseUrl}}/api/quotes HTTP/1.1
Content-Type: application/json

{
    "Text": "Carpe diem.",
    "Author": "Horace",
    "Language": "Latin"
}

### Replace an existing quote
PUT {{baseUrl}}/api/quotes/{{putQuoteId}} HTTP/1.1
Content-Type: application/json

{
    "Text": "Seize the day.",
    "Author": "Horace",
    "Language": "English"
}

### Update an existing quote
PATCH {{baseUrl}}/api/quotes/{{patchQuoteId}} HTTP/1.1
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/Text",
        "value": "Chwytaj dzień."
    },
    {
        "op": "replace",
        "path": "/Language",
        "value": "Polish"
    }
]

### Delete an existing quote
DELETE {{baseUrl}}/api/quotes/{{deleteQuoteId}} HTTP/1.1